### ISSUE TITLE
https://github.com/lazerwalker/tinsel/#language-reference doesn't link to anchor link on page?

### ISSUE THREAD

**Issue by increpare** [lazerwalker/tinsel#11]
Just links to top of page

**Comment by devinmcginty** [comment]
The correct anchor link is `#full-language-reference`. [This link](https://github.com/lazerwalker/tinsel/#full-language-reference) should work.

**Comment by lazerwalker** [comment]
Should be fixed as soon as changes propagate. Thanks @increpare + @devinmcginty :)

**Comment by increpare** [comment]
you forgot 2 files?  (changes submitted)

**Comment by lazerwalker** [comment]
Argh, totally forgot I had it linked anywhere other than the landing page. Thanks!
